name: License Clearance

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build & Restore
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Verify project.assets.json
        run: |
          find . -name project.assets.json

      # Upload the restored project folders as pipeline artifact
      - name: Upload CC input artifact
        uses: actions/upload-artifact@v4
        with:
          name: cc-input
          path: |
            SampleCoreAPI
            SampleCoreAPI.Data

  clearing:
    name: Continuous Clearing
    needs: build
    uses: sumanthkb44/.github/.github/workflows/continuous-clearing.yml@main
